workflows:
  android-workflow:
    name: Maya AI Agent Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      java: 17
    scripts:
      - name: Build Android App
        script: | 
          cd android-app
          chmod +x gradlew
          ./gradlew clean assembleDebug --no-daemon
    artifacts:
      - android-app/app/build/outputs/apk/debug/*.apk
