workflows:
  android-workflow:
    name: AI Agent Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    scripts:
      - name: Build Android App
        script: | 
          # আপনার ফোল্ডারটির নাম অনুযায়ী এখানে পরিবর্তন করা হয়েছে
          cd android-app
          chmod +x gradlew
          ./gradlew clean assembleDebug
    artifacts:
      - android-app/app/build/outputs/apk/debug/*.apk
