workflows:
  android-build:
    name: Final Build Fix
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      java: 17
    scripts:
      - name: Setup and Build
        script: | 
          # ১. রুট ফোল্ডারে (যেখানে মূল প্রোজেক্ট) ফিরে যাওয়া
          cd $CM_BUILD_DIR
          
          # ২. gradlew ফাইল আছে কি না চেক করা এবং সঠিক ডিরেক্টরিতে যাওয়া
          GRADLEW_PATH=$(find . -name gradlew | head -1)
          
          if [ -z "$GRADLEW_PATH" ]; then
            echo "gradlew not found, generating one..."
            # যেখানে build.gradle আছে সেখানে গিয়ে ফাইলটি তৈরি করা
            BUILD_DIR=$(dirname $(find . -name build.gradle | head -1))
            cd $BUILD_DIR
            gradle wrapper
          else
            cd $(dirname "$GRADLEW_PATH")
          fi
          
          # ৩. পারমিশন দিয়ে বিল্ড শুরু করা
          chmod +x gradlew
          ./gradlew assembleDebug --no-daemon
    artifacts:
      - "**/build/outputs/apk/debug/*.apk"
