workflows:
  android-workflow:
    name: Maya AI Agent Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      java: 17
    scripts:
      - name: Build Android App
        script: | 
          cd android-app
          chmod +x gradlew
          # এটি নেটওয়ার্ক এরর এড়িয়ে বিল্ড করার চেষ্টা করবে
          ./gradlew assembleDebug --no-daemon --stacktrace --scan
    artifacts:
      - "**/build/outputs/apk/debug/*.apk"
