workflows:
  android-build:
    name: Auto Fix and Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      java: 17
    scripts:
      - name: Setup and Build
        script: | 
          # ১. যে ফোল্ডারে build.gradle আছে সেখানে যাওয়া
          cd $(dirname $(find . -name build.gradle | head -1))
          
          # ২. যদি gradlew ফাইল না থাকে তবে তৈরি করা
          if [ ! -f "gradlew" ]; then
            gradle wrapper
          fi
          
          # ৩. পারমিশন দেওয়া ও বিল্ড শুরু করা
          chmod +x gradlew
          ./gradlew assembleDebug --no-daemon
    artifacts:
      - "**/build/outputs/apk/debug/*.apk"
