workflows:
  android-workflow:
    name: Final App Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      java: 17
    scripts:
      - name: Build Android App
        script: | 
          chmod +x gradlew
          ./gradlew assembleDebug --no-daemon --stacktrace

    artifacts:
      - "**/build/outputs/apk/debug/*.apk"
