workflows:
  android-workflow:
    name: AI Agent Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    scripts:
      - name: Build Android App
        script: | 
          # ফোল্ডার লোকেশন অটো-ডিটেক্ট করবে
          find . -name "gradlew" -exec chmod +x {} +
          
          # প্রজেক্ট রুট থেকে বিল্ড শুরু করবে
          if [ -d "android" ]; then
            cd android && ./gradlew assembleDebug
          else
            ./gradlew assembleDebug
          fi
    artifacts:
      - "**/build/outputs/apk/debug/*.apk"
