workflows:
  android-build:
    name: Android Build Fix
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      java: 17
    scripts:
      - name: Setup and Build
        script: | 
          # ১. রুট ফোল্ডারে যাওয়া
          cd $CM_BUILD_DIR
          
          # ২. gradlew ফাইল আছে কি না চেক করা এবং সঠিক ডিরেক্টরিতে যাওয়া
          # যদি ফাইলটি পাওয়া যায়, তবে সেই ফোল্ডারে যাও
          GRADLEW_PATH=$(find . -name gradlew | head -1)
          
          if [ -n "$GRADLEW_PATH" ]; then
            echo "Found gradlew at $GRADLEW_PATH"
            cd $(dirname "$GRADLEW_PATH")
          else
            echo "gradlew not found, trying to find build.gradle"
            # যদি gradlew না থাকে তবে যেখানে build.gradle আছে সেখানে গিয়ে তৈরি করার চেষ্টা করা
            BUILD_GRADLE_PATH=$(find . -name build.gradle | head -1)
            if [ -n "$BUILD_GRADLE_PATH" ]; then
                cd $(dirname "$BUILD_GRADLE_PATH")
                gradle wrapper
            else
                echo "Error: No Android project found!"
                exit 1
            fi
          fi
          
          # ৩. পারমিশন দিয়ে এবং ক্যাশ মেমোরি ছাড়াই বিল্ড শুরু করা
          chmod +x gradlew
          ./gradlew clean assembleDebug --no-daemon
    artifacts:
      - "**/build/outputs/apk/debug/*.apk"
