workflows:
  android-debug-build:
    name: AI Agent APK Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    scripts:
      - name: Build Android App
        script: |
          cd android
          chmod +x gradlew
          ./gradlew clean assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
