workflows:
  android-release:
    name: Build APK (release)
    environment:
      vars:
        # Provide these as encrypted vars in Codemagic settings
        KEYSTORE_BASE64: Encrypted:YOUR_KEYSTORE_BASE64
        KEYSTORE_PASSWORD: Encrypted:YOUR_KEYSTORE_PASS
        KEY_ALIAS: Encrypted:YOUR_KEY_ALIAS
        KEY_PASSWORD: Encrypted:YOUR_KEY_PASS
    scripts:
      - name: Prepare environment
        script: |
          #!/bin/bash
          set -e
          echo "Setting up environment"
      - name: Decode keystore
        script: |
          if [ -n "$KEYSTORE_BASE64" ]; then
            echo "$KEYSTORE_BASE64" | base64 -d > /tmp/keystore.jks
          fi
      - name: Build
        script: |
          chmod +x ./gradlew || true
          ./gradlew clean assembleRelease -Pandroid.injected.signing.store.file=/tmp/keystore.jks -Pandroid.injected.signing.store.password="$KEYSTORE_PASSWORD" -Pandroid.injected.signing.key.alias="$KEY_ALIAS" -Pandroid.injected.signing.key.password="$KEY_PASSWORD"
    artifacts:
      - app/build/outputs/apk/release/*.apk
    publishing:
      email:
        recipients:
          - you@example.com
